version = 1

exclude_patterns = [
  "tests/**",
  "bin/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["vitest"]

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"